version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DEV_SOCIAL_NET_WORK
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  dev_social_network:
    image: dev_social_network
    build: .
    container_name: dev_social_network
    ports:
      - 5000:5000
    environment:
      DB_HOST: mysql_db