USE DEV_SOCIAL_NET_WORK;

CREATE TABLE USER(
    ID VARCHAR(250) PRIMARY KEY,
    NAME VARCHAR(500) NOT NULL,
    NICK_NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(500) NOT NULL UNIQUE,
    PASSWORD VARCHAR(500) NOT NULL UNIQUE,
    CREATED_AT DATETIME 
);

CREATE TABLE FOLLOWERS(
    ID_USER VARCHAR(250),
    ID_FOLLOWING VARCHAR(250),

    FOREIGN KEY (ID_USER) REFERENCES USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_FOLLOWING) REFERENCES USER(ID) ON DELETE CASCADE,
    PRIMARY KEY (ID_USER, ID_FOLLOWING)
);